# Generated by Django 3.1.4 on 2021-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'social_users',
            },
        ),
    ]
