# Generated by Django 3.1.4 on 2021-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='id_card_photo',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='profile_photo',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
