# Generated by Django 3.1.4 on 2021-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210201_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
