# Generated by Django 3.1.4 on 2021-02-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_socialuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='profile_photo',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
