# Generated by Django 3.1.4 on 2021-01-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='accuracy',
            new_name='accuracy_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='check_in',
            new_name='check_in_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='cleanliness',
            new_name='cleanliness_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='communication',
            new_name='communication_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='image_url',
            new_name='image_url_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='location',
            new_name='location_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='value_score',
        ),
        migrations.RemoveField(
            model_name='bedroom',
            name='bedroom',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='space',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='max_people',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
