# Generated by Django 3.1.4 on 2021-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancellation_flexibility',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_with_host',
        ),
        migrations.AddField(
            model_name='space',
            name='card',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='is_with_host',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='is_work_trip',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='trip_purpose',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
