# Generated by Django 3.1.4 on 2021-02-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20210201_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='letitude',
            new_name='latitude',
        ),
    ]
